### PR TITLE
Link to OWASP Vulnerability Scanning Tools

### PR DESCRIPTION
**Pull request by OlivierJaquemet**
Add external link to OWASP "Vulnerability Scanning Tools" which includes more tools

### CODE REVIEW

**Review by psiinon — COMMENTED** [review]
Does this add anything more than the other OWASP link, apart from more paid for commercial tools?

**Comment by psiinon** [comment]
Oh, which ones? Would be good to add them if they are on github ...

**Comment by OlivierJaquemet** [comment]
Here are the Open Source scanner listed on that page that are on GitHub and not yet on your list :

- [Deepfence ThreatMapper](https://github.com/deepfence/ThreatMapper)	
- [OpenVAS by Greenbone](https://github.com/greenbone/openvas-scanner)
- [OWASP PurpleTeam](https://github.com/purpleteam-labs)
- [Adobe Ride (REST JSON Payload fuzzer)](https://github.com/adobe/ride/blob/develop/Usage.md#the-fuzz)
- [VWT Digital Sec-helpers] https://github.com/vwt-digital/sec-helpers/

There are others Open source scanner in the OWASP list, but not on GitHub

**Comment by psiinon** [comment]
Thanks!
So

- [Deepfence ThreatMapper](https://github.com/deepfence/ThreatMapper) = Infrastructure?
- [OpenVAS by Greenbone](https://github.com/greenbone/openvas-scanner) = Infrastructure?
- [Adobe Ride (REST JSON Payload fuzzer)](https://github.com/adobe/ride/blob/develop/Usage.md#the-fuzz) = Fuzzer?
- [VWT Digital Sec-helpers](https://github.com/vwt-digital/sec-helpers/) = Infrastructure?

I thought [OWASP PurpleTeam](https://github.com/purpleteam-labs) was a wrapper around other tools (like ZAP) - I dont really want to track those as well ;) Or does it do any of its own scanning? (if you know)

**Comment by psiinon** [comment]
I'll check - I know the author ;)
And will add the others when I get the chance, unless you fancy PR'ing them? ;)
Thanks for the feedback!

**Pull request merged**
