### PR TITLE
Added three more tools

### PR DESCRIPTION
**Pull request by 0x-Apollyon**
Added the following
Mongoaudit: Utility for scanning mongodb based backends
Fuxploider: Utility for file upload vulns
LFIScanner: Utility for local file inclusion vulns

### CODE REVIEW

**Review by psiinon — CHANGES_REQUESTED** [review]
Mongoaudit looks like the db specific rather than being related to web apps.
The other 2 look good though.

**Comment by 0x-Apollyon** [comment]
MongoDB is very very popular NoSQL though and used by a ton of webapps. I think it should be included in the list as a pentester will encounter mongo every now and then. 
Lmk your thoughts

**Comment by psiinon** [comment]
Understood, but its a different work of tool. I've pushed back on tracking web crawlers for similar reasons, and because there are so many of them.
Openning this up to db security tools will mean more research (for other similar tools), more work maintaining the list, and it would be harder for me to justify not adding other types of security tools.
So for now I do want to keep it just to OSS web scanners...

**Comment by 0x-Apollyon** [comment]
Did the requested changes

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Thanks!

**Pull request merged**
